name: pipeline revisão

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: fazendo clone do repo
        uses: actions/checkout@v3

      - name: configurando python
        uses: actions/setup-python@v4

      - name: instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: rodando os testes
        run: pytest
        
