name: pipeline revisão

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: fazendo clone do repo
        uses: actions/checkout@v3

      - name: configurando python
        uses: actions/setup-python@v4

      - name: instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: rodando os testes
        run: pytest
      
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "usr-crkd6qhu0jms73bk598g"}' \
            https://api.render.com/v1/services/usr-crkd6qhu0jms73bk598g/deploys

